# Use Node.js LTS version
FROM node:22.13.1-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy project files
COPY . .

# Expose Vite's port
EXPOSE 5174

# Start in development mode
CMD ["npm", "run", "dev", "--", "--host"]